### ISSUE TITLE
Workspaces that I can't access are returned from GET /workspace

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/girder_wholetale#239] opened 2019-02-14 22:42 UTC
### Steps to Reproduce
1. Launch a Tale that you don't own
2. Navigate to Run > Files > Tale Workspaces
    * NOTE: list is empty
3. Choose (+) > New Folder, enter a name (e.g. `test123`), and submit the form
    * NOTE: state is now desynced with view
    * NOTE: The same behavior can be observed with Run > Files > Tale Workspaces > (+) > Upload File

### Expected Results
* New Folder is uploaded to Tale Workspace
* Tale Workspaces still selected
* Tale Workspaces resynced and shown in the list

### Actual Results
* New Folder is uploaded to Home folder
* Tale Workspaces still selected
* View is desynced from state, and now shows the Home folder (or possibly a subset)

**Comment by Xarthisius** [comment] 2019-02-15 19:11
I can't reproduce this, I get
1. `POST https://girder.local.wholetale.org/api/v1/folder?parentType=folder&parentId=5c6709230d137c00012401f0&name=blah 403` for create folder
1. `POST https://girder.local.wholetale.org/api/v1/file 403` for file upload
on a public tale that's owned by different user. Tale Workspace remains empty in the dashboard.

**Comment by ThomasThelen** [comment] 2019-02-15 19:20
I see Mike's behavior on stage,

`HTTP/2.0 200 OK https://girder.stage.wholetale.org/api/v1/folder?parentType=folder&parentId=5b7f14e84145320001601780&name=asdfg`

`HTTP/2.0 200 OK https://girder.stage.wholetale.org/api/v1/file`

The folder will end up in my home directory rather than the workspace. Note that this is for a Tale that I don't own, it works fine when doing this on my own Tale.

**Comment by Xarthisius** [comment] 2019-02-15 19:34
OK, I see that on stage. Workspace access level do not match Tale access level. E.g.
For a public tale (5b562a1f4f3e9f004120a32b) its workspace (5b48ce4f715d3400011e9c68) is actually private and accessible only to owner. Inconsistencies like that need to be fixed in the db.
However, all that happens later (defaulting subsequent requests to user's Home) is happening somewhere in the UI.

**Comment by Xarthisius** [comment] 2019-03-22 01:31
I believe this was fixed by applying https://github.com/whole-tale/girder_wholetale/blob/master/scripts/tale_acls_fix.py

**Closed by Xarthisius** 2019-03-22 01:31 UTC
